# Generated by Django 2.2.2 on 2019-07-07 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reserve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserve_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
