# Generated by Django 2.2.2 on 2019-06-13 05:02

from django.db import migrations, models
import django.db.models.deletion
import local.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSoccer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, max_length=150, null=True)),
                ('material_type', models.PositiveIntegerField(choices=[(0, 'Grass Sintetico'), (1, 'Grass Natural'), (2, 'Plataforma de Tierra'), (3, 'Plataforma de Cemento')], default=0)),
                ('total_reserves', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=local.utils.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=225)),
                ('district_ubigeo', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court_soccer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_soccer_schedule', to='local.CourtSoccer')),
            ],
        ),
    ]
