# Generated by Django 2.2.2 on 2019-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_auto_20190613_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsoccer',
            name='slug',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='slug',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
