# Generated by Django 2.2.2 on 2019-06-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserve', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order', to='reserve.Reserve'),
        ),
    ]
